<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>me.sirrahmas</groupId>
    <artifactId>ndcmap</artifactId>
    <version>1.0-SNAPSHOT</version>
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.release>25</maven.compiler.release>
        <exec.mainClass>me.sirrahmas.ndcmap.NDCMap</exec.mainClass>
    </properties>

    <dependencies>
        <!-- 
            Web framework. 
            Source: https://mvnrepository.com/artifact/io.javalin/javalin
        -->
        <dependency>
            <groupId>io.javalin</groupId>
            <artifactId>javalin</artifactId>
            <version>7.2.0</version>
            <scope>compile</scope>
        </dependency>

        <!--
            Database engine.
            Source: https://mvnrepository.com/artifact/com.arcadedb/arcadedb-engine
        -->
        <dependency>
            <groupId>com.arcadedb</groupId>
            <artifactId>arcadedb-engine</artifactId>
            <version>26.4.2</version>
            <scope>compile</scope>
        </dependency>

        <!--
            Database import/export.
            Source: https://mvnrepository.com/artifact/com.arcadedb/arcadedb-integration 
        -->
        <dependency>
            <groupId>com.arcadedb</groupId>
            <artifactId>arcadedb-integration</artifactId>
            <version>26.4.2</version>
            <scope>compile</scope>
        </dependency>

        <!--
            Unit test framework.
            Source: https://mvnrepository.com/artifact/org.junit.jupiter/junit-jupiter-api
        -->
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <version>6.0.3</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <artifactId>maven-resources-plugin</artifactId>
                <version>3.5.0</version>
                <configuration>
                    <resources>
                        <directories>
                            <directory>/resources</directory>
                        </directories>
                    </resources>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>